# Generated by Django 3.2.8 on 2021-10-27 21:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_project_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=core.models.project_image_file_path),
        ),
    ]
