# Generated by Django 3.2.8 on 2021-10-28 17:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.FileField(null=True, upload_to=core.models.project_data_file_path),
        ),
    ]
