# Generated by Django 3.2.8 on 2021-11-14 20:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified_data_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_thumbnail_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None),
        ),
    ]
