# Generated by Django 3.2.8 on 2021-11-14 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211114_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modified_date_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, null=True, size=None),
        ),
    ]
