# Generated by Django 3.2.9 on 2021-12-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211201_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='tool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tool'),
        ),
    ]
