# Generated by Django 3.2.9 on 2021-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_software_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='tool',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
