# Generated by Django 3.2.9 on 2021-12-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_software_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='tool',
        ),
    ]
