# Generated by Django 3.2.9 on 2021-12-01 19:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_software_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='default_file',
            field=models.FileField(null=True, upload_to=core.models.software_data_file_path),
        ),
    ]
